server:
  port: 8012

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/makeup?serverTimezone=Asia/Seoul
    username: root
    password: qwe123
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: clothes

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  redis:
#    host: ENC(G6L03YghvQxiq9YSUngL51alhdDqZcJI)
#    port: 6379

jwt:
  secret: ENC(NumiU4LB6bpLOCSPlp6Ob5pDZICXItQDfvb66DmVCNdUdMYKmR/O7FDxdP8AVSVCLUUzEUG8LkWUuPK14u2ejw==)

#trace: true

springdoc:
  api-docs:
    path: /static-service/v3/api-docs
  swagger-ui:
    path: /static-service/swagger-ui.html

openapi:
  service:
    url: http://localhost:8000/

jasypt:
  encryptor:
    password: ${PASSWORD}