server:
  port: 8012

spring:
  application:
    name: static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/makeup?serverTimezone=Asia/Seoul
    url: jdbc:mysql://k9d204.p.ssafy.io:3306/makeup?serverTimezone=Asia/Seoul
    username: root
#    password: ENC(ruBvYLBdp/4OQHTchrz3FA==)
    password: ENC(I8bqm0Jc8Ox/Cv1GmVCGWo5T9p4IlbQ9)
#    password: qwe123

  data:
    mongodb:
#      host: localhost
      host: k9d204.p.ssafy.io
      port: 27017
      database: clothes
      username: root
      password: ENC(I8bqm0Jc8Ox/Cv1GmVCGWo5T9p4IlbQ9)
      authentication-database: admin

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
#      host: ENC(G6L03YghvQxiq9YSUngL51alhdDqZcJI)
    host: k9d204.p.ssafy.io
    port: 6379

jwt:
  secret: ENC(NumiU4LB6bpLOCSPlp6Ob5pDZICXItQDfvb66DmVCNdUdMYKmR/O7FDxdP8AVSVCLUUzEUG8LkWUuPK14u2ejw==)

#trace: true

springdoc:
  api-docs:
    path: /static-service/v3/api-docs
  swagger-ui:
    path: /static-service/swagger-ui.html

openapi:
  service:
    url: http://k9d204a.p.ssafy.io:8000/
#    url: http://localhost:8000/

jasypt:
  encryptor:
    password: ${PASSWORD}